# Site settings

title: 'Heart Narongrit Kanhanoi — Software Engineer, CTO'
description: 'Sharing technical knowledge, ideas, and insights across software engineering, AI, and system design.'
url: 'https://heart.github.io'
baseurl: ''
author: 'Heart Narongrit Kanhanoi'
github_username: 'heart'

# Build settings
theme: minima
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
